SELECT TO_CHAR(HIRE_DATE, 'YYYY') AS HIRE_YEAR,
COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'YYYY')
ORDER BY TO_CHAR(HIRE_DATE, 'YYYY');

SELECT PERIOD, REGION, SUM(LOAN_JAN_AMT)
FROM KOR_LOAN_STATUS
WHERE PERIOD LIKE '2012%'
GROUP BY PERIOD, REGION
ORDER BY PERIOD, REGION;

SELECT PERIOD, GUBUN, SUM(LOAN_JAN_AMT) TOTL_JAN
FROM KOR_LOAN_STATUS
WHERE PERIOD LIKE '2013%'
GROUP BY PERIOD, ROLLUP(GUBUN);

SELECT PERIOD, GUBUN, SUM(LOAN_JAN_AMT) TOTL_JAN
FROM KOR_LOAN_STATUS
WHERE PERIOD LIKE '2013%'
GROUP BY PERIOD, GUBUN
UNION
SELECT PERIOD, '', SUM(LOAN_JAN_AMT) TOTL_JAN
FROM KOR_LOAN_STATUS
WHERE PERIOD LIKE '2013%'
GROUP BY PERIOD;

SELECT period,
    CASE WHEN GUBUN = '주택담보대출' THEN SUM(LOAN_JAN_AMT) ELSE 0 END AS 주택담보대출액,
    CASE WHEN GUBUN = '기타대출' THEN SUM(LOAN_JAN_AMT) ELSE 0 END AS 기타대출액
FROM KOR_LOAN_STATUS
WHERE period = '201311'
GROUP BY period, GUBUN;

SELECT PERIOD, 0 주택담보대출액, SUM(LOAN_JAN_AMT) AS 기타대출액
FROM KOR_LOAN_STATUS
WHERE PERIOD = '201311'
AND GUBUN = '기타대출'
GROUP BY PERIOD, GUBUN
UNION ALL
SELECT PERIOD, SUM(LOAN_JAN_AMT) AS 주택담보대출액, 0 기타대출액
FROM KOR_LOAN_STATUS
WHERE PERIOD = '201311'
AND GUBUN = '주택담보대출'
GROUP BY PERIOD, GUBUN;

SELECT REGION,
    SUM(AMT1) AS "201111",
    SUM(AMT2) AS "201112",
    SUM(AMT3) AS "201210",
    SUM(AMT4) AS "201211",
    SUM(AMT5) AS "201212",
    SUM(AMT6) AS "201310",
    SUM(AMT7) AS "201311"
    
FROM (
    SELECT REGION,
        CASE WHEN period = '201111' THEN LOAN_JAN_AMT ELSE 0 END AS AMT1,
        CASE WHEN period = '201112' THEN LOAN_JAN_AMT ELSE 0 END AS AMT2,
        CASE WHEN period = '201210' THEN LOAN_JAN_AMT ELSE 0 END AS AMT3,
        CASE WHEN period = '201211' THEN LOAN_JAN_AMT ELSE 0 END AS AMT4,
        CASE WHEN period = '201212' THEN LOAN_JAN_AMT ELSE 0 END AS AMT5,
        CASE WHEN period = '201310' THEN LOAN_JAN_AMT ELSE 0 END AS AMT6,
        CASE WHEN period = '201311' THEN LOAN_JAN_AMT ELSE 0 END AS AMT7
    FROM KOR_LOAN_STATUS
    )  
GROUP BY REGION
ORDER BY REGION;

SELECT EMPLOYEE_ID,
LPAD(SUBSTR(PHONE_NUMBER, 5), 12, '(02)')
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, EMP_NAME, HIRE_DATE, ROUND((SYSDATE - HIRE_DATE)/365) AS YEAR_OF_SERVICES
FROM EMPLOYEES
WHERE ROUND((SYSDATE - HIRE_DATE)/365) >= 10
ORDER BY ROUND((SYSDATE - HIRE_DATE)/365) DESC;

SELECT CUST_MAIN_PHONE_NUMBER,
    REPLACE(CUST_MAIN_PHONE_NUMBER, '-', '/')
FROM CUSTOMERS;

SELECT CUST_NAME, CUST_MAIN_PHONE_NUMBER,
    TRANSLATE(CUST_MAIN_PHONE_NUMBER, '0123456789', 'QWERTYUIOP') AS SECRET_NUMBER
FROM CUSTOMERS;

CREATE TABLE SAMPLE (
    CUST_NAME VARCHAR2(100),
    CUST_NEW_PHONE_NUMBER VARCHAR2(25)
);

CREATE TABLE SAMPLE AS
SELECT CUST_NAME, CUST_MAIN_PHONE_NUMBER,
    TRANSLATE(CUST_MAIN_PHONE_NUMBER, '0123456789', 'QWERTYUIOP') AS SECRET_NUMBER
FROM CUSTOMERS;

ALTER TABLE SAMPLE DROP COLUMN CUST_MAIN_PHONE_NUMBER;

SELECT CUST_NAME, SECRET_NUMBER,
    TRANSLATE(SECRET_NUMBER, 'QWERTYUIOP', '0123456789') AS NEW_PHONE_NUMBER
FROM SAMPLE;

DROP TABLE SAMPLE;


INSERT INTO SAMPLE 
SELECT CUST_NAME, CUST_MAIN_PHONE_NUMBER,
    TRANSLATE(CUST_MAIN_PHONE_NUMBER, '0123456789', 'QWERTYUIOP') AS NEW_PHONE_NUMBER
FROM CUSTOMERS;



SELECT CUST_NAME, CUST_YEAR_OF_BIRTH,
DECODE(TRUNC((TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)/10), 3, '30대',
                                                                 4, '40대',
                                                                 5, '50대',
                                                                 '기타') GENERATION
FROM CUSTOMERS;

SELECT CUST_NAME, CUST_YEAR_OF_BIRTH,
    CASE WHEN TRUNC((TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '1' THEN '10대'
     WHEN TRUNC((TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '2' THEN '20대'
     WHEN TRUNC((TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '3' THEN '30대'
     WHEN TRUNC((TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '4' THEN '40대'
     WHEN TRUNC((TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '5' THEN '50대'
     WHEN TRUNC((TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '6' THEN '60대'
     WHEN TRUNC((TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '7' THEN '70대'
     WHEN TRUNC((TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '8' THEN '80대'
     WHEN TRUNC((TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '9' THEN '90대'
     ELSE '기타' END AS NEW_GENERATION
FROM CUSTOMERS;


SELECT a.employee_id, a.emp_name, a.department_id, b.department_name
FROM employees a,
    departments b
WHERE a.department_id = b.department_id;

SELECT department_id, department_name
FROM departments a
WHERE EXISTS(SELECT *
            FROM employees b
            WHERE a.department_id = b.department_id
            AND b.salary > 3000)
ORDER BY a.department_name;

SELECT department_id, department_name
FROM departments a
WHERE a.department_id IN (SELECT b.department_id
                            FROM employees b
                            WHERE b.salary > 3000)
ORDER BY department_name;



SELECT TO_CHAR(HIRE_DATE, 'YYYY'),
COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'YYYY')
ORDER BY TO_CHAR(HIRE_DATE, 'YYYY');

SELECT PERIOD, REGION, SUM(LOAN_JAN_AMT)
FROM KOR_LOAN_STATUS
WHERE PERIOD LIKE '2012%'
GROUP BY PERIOD, REGION
ORDER BY PERIOD, REGION;

SELECT PERIOD, GUBUN, SUM(LOAN_JAN_AMT) TOTL_JAN
FROM KOR_LOAN_STATUS
WHERE PERIOD LIKE '2013%'
GROUP BY ROLLUP(PERIOD), GUBUN;

SELECT '', GUBUN, SUM(LOAN_JAN_AMT) TOTL_JAN
FROM KOR_LOAN_STATUS
WHERE PERIOD LIKE '2013%'
GROUP BY GUBUN
UNION
SELECT PERIOD, GUBUN, SUM(LOAN_JAN_AMT) TOTL_JAN
FROM KOR_LOAN_STATUS
WHERE PERIOD LIKE '2013%'
GROUP BY PERIOD, GUBUN;

SELECT PERIOD, SUM(LOAN_JAN_AMT) 주택담보대출액, 0 기타대출액
FROM KOR_LOAN_STATUS
WHERE PERIOD = '201311'
AND GUBUN = '주택담보대출'
GROUP BY PERIOD, GUBUN
UNION ALL
SELECT PERIOD, 0 주택담보대출액, SUM(LOAN_JAN_AMT) 기타대출액
FROM KOR_LOAN_STATUS
WHERE PERIOD = '201311'
AND GUBUN = '기타대출'
GROUP BY PERIOD, GUBUN;

SELECT REGION,
    SUM(AMT1) AS "201111",
    SUM(AMT2) AS "201112",
    SUM(AMT3) AS "201210",
    SUM(AMT4) AS "201211",
    SUM(AMT5) AS "201212",
    SUM(AMT6) AS "201310",
    SUM(AMT7) AS "201311"
FROM(
SELECT REGION,
    CASE WHEN PERIOD='201111' THEN LOAN_JAN_AMT ELSE 0 END AMT1,
    CASE WHEN PERIOD='201112' THEN LOAN_JAN_AMT ELSE 0 END AMT2,
    CASE WHEN PERIOD='201210' THEN LOAN_JAN_AMT ELSE 0 END AMT3,
    CASE WHEN PERIOD='201211' THEN LOAN_JAN_AMT ELSE 0 END AMT4,
    CASE WHEN PERIOD='201212' THEN LOAN_JAN_AMT ELSE 0 END AMT5,
    CASE WHEN PERIOD='201310' THEN LOAN_JAN_AMT ELSE 0 END AMT6,
    CASE WHEN PERIOD='201311' THEN LOAN_JAN_AMT ELSE 0 END AMT7
    FROM KOR_LOAN_STATUS
    )
GROUP BY REGION
ORDER BY REGION;
    
SELECT EMPLOYEE_ID,
LPAD(SUBSTR(PHONE_NUMBER, 5), 12, '(02)')
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, EMP_NAME, HIRE_DATE, (TO_CHAR(SYSDATE, 'YYYY') - TO_CHAR(HIRE_DATE, 'YYYY')) AS WORK_YEAR
FROM EMPLOYEES
WHERE (TO_CHAR(SYSDATE, 'YYYY') - TO_CHAR(HIRE_DATE, 'YYYY')) >= 10
ORDER BY (TO_CHAR(SYSDATE, 'YYYY') - TO_CHAR(HIRE_DATE, 'YYYY')) DESC;

SELECT CUST_MAIN_PHONE_NUMBER,
REPLACE(CUST_MAIN_PHONE_NUMBER, '-', '/')
FROM CUSTOMERS;

SELECT CUST_MAIN_PHONE_NUMBER,
TRANSLATE(CUST_MAIN_PHONE_NUMBER, '0123456789', 'QWERTYUIOP') AS SECRET
FROM CUSTOMERS;

SELECT CUST_YEAR_OF_BIRTH,
DECODE(TRUNC((TO_CHAR(SYSDATE,'YYYY')- CUST_YEAR_OF_BIRTH)/10), 3, '30대',
                                                               4, '40대',
                                                               5, '50대',
                                                               '기타') 세대
FROM CUSTOMERS;

SELECT CUST_YEAR_OF_BIRTH,
    CASE WHEN TRUNC((TO_CHAR(SYSDATE,'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '1' THEN '10대'
        WHEN TRUNC((TO_CHAR(SYSDATE,'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '2' THEN '20대'
        WHEN TRUNC((TO_CHAR(SYSDATE,'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '3' THEN '30대'
        WHEN TRUNC((TO_CHAR(SYSDATE,'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '4' THEN '40대'
        WHEN TRUNC((TO_CHAR(SYSDATE,'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '5' THEN '50대'
        WHEN TRUNC((TO_CHAR(SYSDATE,'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '6' THEN '60대'
        WHEN TRUNC((TO_CHAR(SYSDATE,'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '7' THEN '70대'
        WHEN TRUNC((TO_CHAR(SYSDATE,'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '8' THEN '80대'
        WHEN TRUNC((TO_CHAR(SYSDATE,'YYYY') - CUST_YEAR_OF_BIRTH)/10) = '9' THEN '90대'
    ELSE '기타' END AS 세대
FROM CUSTOMERS;
        
SELECT CUST_NAME, CUST_MAIN_PHONE_NUMBER,
    TRANSLATE(CUST_MAIN_PHONE_NUMBER, '0123456789', 'QWERTYUIOP') AS SECRET_NUMBER
FROM CUSTOMERS;

CREATE TABLE SAMPLE (
    CUST_NAME VARCHAR2(100),
    CUST_NEW_PHONE_NUMBER VARCHAR2(25)
);

CREATE TABLE SAMPLE AS
SELECT CUST_NAME, CUST_MAIN_PHONE_NUMBER,
    TRANSLATE(CUST_MAIN_PHONE_NUMBER, '0123456789', 'imastudent') AS SECRET_NUMBER
FROM CUSTOMERS;

ALTER TABLE SAMPLE DROP COLUMN CUST_MAIN_PHONE_NUMBER;

SELECT CUST_NAME, SECRET_NUMBER,
    TRANSLATE(SECRET_NUMBER, 'QWERTYUIOP', '0123456789') AS PHONE_NUMBER
FROM SAMPLE;

DROP TABLE SAMPLE;